### ISSUE TITLE
Error when initiating transaction

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#292]
Multiple users reported this error upon initiating any action that requires a transaction.

`useProposeDelegationChange.ts:46 UnconfiguredSignerError: No signer has been configured. Please configure one by calling setProvider({signer}) on your TezosToolkit instance.
    at create-observable-from-subscription.ts:21:11
    at l (transformData.js:63:40)
    at Generator._invoke (transformData.js:294:22)
    at Generator.next (transformData.js:119:21)
    at 2.154995d2.chunk.js:2:872996
    at new Promise (<anonymous>)
    at sn (2.154995d2.chunk.js:2:872741)
    at e.value (2.154995d2.chunk.js:2:873812)
    at e.<anonymous> (contract-method-object-param.ts:15:32)
    at l (transformData.js:63:40)`

**Comment by EightRice** [comment]
Fixed with the last merge.
