### ISSUE TITLE
Can't create DAO using self-service option

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#767]
After setting all the parameters and clicking `deploy DAO`, the wallet brings up the transaction as expected, and after approving it, the app instantly moves to step two and then fails:

<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a3de690604b0f23a2545ff6d3a99d66d36509e1/image.png" alt="image.png" />

And the console shows these messages:

`Making storage contract...
class.ts:117 error  SyntaxError: Unexpected token '<', "
<!-- HTML "... is not valid JSON
Review.tsx:73 Error: Error deploying DAO
    at class.ts:118:13
    at l (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.throw (regeneratorRuntime.js:69:21)
    at Sr (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)`

**Comment by akdorg** [comment]
This issue may be caused by our deployments on AWS.

**Comment by akdorg** [comment]
Currently in Review at following link
https://github.com/dOrgTech/baseDAO-dockerized/pull/8
