### ISSUE TITLE
Can't submit proposal

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#799]

**Comment by EightRice** [comment]
**Can't submit a proposal**
**How big of an impact does this have on your activity?**
* HIGH - Can't perform one or more critical actions

**Specify the steps to reproduce this issue**
* Create a proposal in lite DAO

**Describe the unexpended behavior in contrast to what should normally happen in the app**
* Spinning wheel when trying to create a proposal

**Paste the full URL that the browser is on when the issue occurs**
* https://tezos-homebase.io/explorer/lite/dao/65ded99a5d3d7a9c8151fa2e/community/proposal

**The wallet address you are using in the app**
* tz1ahk6K5RPFChRxJWyN8hWJdKpsSMjDBWF9
 
**What wallet are you using?**
* Umami

**On which network is the issue occurring?**
* Mainnet

**If you have a stack trace from the browser console, or a error from the wallet, paste it here. (To capture the stack trace, open Developer Options in your browser and go to the Console tab).**
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index.tsx:28 ALL CLOSED
events.launchdarkly.com/events/diagnostic/6335cf04387f5e11ca071b58:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.launchdarkly.com/events/diagnostic/6335cf04387f5e11ca071b58:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Utils.ts:188 [2024-03-07T03:10:26.758Z] Information: WebSocket connected to wss://api.mainnet.tzkt.io/v1/events?id=7o0kTdhUV-0JTN77L_YFbQ.
events.ts:421 showPairAlert
index.js:1016 WC LOADED
index.js:1013 P2P LOADED
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
DAppClient.ts:231 ### openRequest ### e
DAppClient.ts:233 ### message ### {"type":"acknowledge","version":"2","senderId":"Y8xURfrNHQ4q","id":"cdb9ee36-7a4e-6fe4-96e3-a7455ff3973e"}
DAppClient.ts:234 ### connectionInfo ### Object
DAppClient.ts:231 ### openRequest ### e
DAppClient.ts:233 ### message ### {"senderId":"Y8xURfrNHQ4q","version":"2","appMetadata":{"senderId":"Y8xURfrNHQ4q","name":"Umami","icon":""},"type":"permission_response","network":{"type":"mainnet"},"scopes":["operation_request","sign"],"id":"cdb9ee36-7a4e-6fe4-96e3-a7455ff3973e","publicKey":"edpkuug61aKtr8jZsyiREy8h15vJfZYuBnYpEMBNx5bDocXiyL2VGa"}
DAppClient.ts:234 ### connectionInfo ### Object
Logger.ts:35 cdb9ee36-7a4e-6fe4-96e3-a7455ff3973e: 10229.510009765625 ms
DAppClient.ts:1834 ######## MESSAGE #######
DAppClient.ts:1835 Object
DAppClient.ts:1856 ######## ACCOUNT INFO #######
DAppClient.ts:1858 {"accountIdentifier":"2JrKnV6hnDzJTk35GC5D","senderId":"Y8xURfrNHQ4q","origin":{"type":"p2p","id":"11785c73f6c8378c7542d564dfc8c45f358816500933b83f2218decc64d90b46"},"walletKey":"umami_desktop","address":"tz1ahk6K5RPFChRxJWyN8hWJdKpsSMjDBWF9","publicKey":"edpkuug61aKtr8jZsyiREy8h15vJfZYuBnYpEMBNx5bDocXiyL2VGa","network":{"type":"mainnet"},"scopes":["operation_request","sign"],"connectedAt":1709781039415}
query.js:358 Error: Address tz1ahk6K5RPFChRxJWyN8hWJdKpsSMjDBWF9 has no profile in network mainnet
    at index.ts:20:11
    at l (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at Sr (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)
onError @ query.js:358
Show 1 more frame
Show less
index.tsx:727 Object
jsonrpc.ts:29 Uncaught (in promise) Error
    at jsonrpc.ts:29:23
events.launchdarkly.com/events/diagnostic/6335cf04387f5e11ca071b58:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.launchdarkly.com/events/diagnostic/6335cf04387f5e11ca071b58:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
If you have a relevant screenshot, upload it here

**Any other comments?**
This was using Arc Browser. I've also tried Brave browser with shields down with Temple wallet. Same issue.
